# Generated by Django 3.2.10 on 2022-09-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organizationinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='company_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
