# Generated by Django 3.2.10 on 2022-09-14 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_abstractorganizationjoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='unique_business',
            field=models.ForeignKey(blank=True, default=None, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.abstractorganizationjoin'),
        ),
        migrations.AddField(
            model_name='organization',
            name='user_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
