# Generated by Django 3.2.10 on 2022-09-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_auto_20220914_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(default=None, max_length=200)),
                ('company_number', models.IntegerField(default=None)),
                ('company_website', models.URLField(default=None)),
                ('company_industry', models.CharField(default=None, max_length=200)),
                ('company_address', models.CharField(default=None, max_length=200)),
                ('name', models.CharField(default=None, max_length=200)),
                ('job_title', models.CharField(default=None, max_length=200)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('email_verified', models.BooleanField(blank=True, null=True)),
                ('contact_no', models.CharField(default=None, max_length=200)),
                ('agree', models.BooleanField()),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='organization',
            name='unique_business',
        ),
        migrations.DeleteModel(
            name='AbstractOrganizationJoin',
        ),
    ]
