# Generated by Django 3.2.10 on 2023-02-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_auto_20230204_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='board_name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
