# Generated by Django 3.2.10 on 2023-02-04 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_board_board_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(default=None, max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('class_name', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Board',
                'verbose_name_plural': 'Board',
            },
        ),
        migrations.CreateModel(
            name='Floors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(default=None, max_length=200)),
                ('board', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.building')),
            ],
            options={
                'verbose_name': 'Floor',
                'verbose_name_plural': 'Floors',
            },
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='board',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
