# Generated by Django 3.2.10 on 2023-02-04 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_auto_20230204_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'Building', 'verbose_name_plural': 'Buildings'},
        ),
        migrations.RenameField(
            model_name='building',
            old_name='board_name',
            new_name='building_name',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='class_name',
            new_name='organization_name',
        ),
        migrations.RenameField(
            model_name='floors',
            old_name='board',
            new_name='building',
        ),
        migrations.RenameField(
            model_name='floors',
            old_name='subject_name',
            new_name='floor_name',
        ),
    ]
