# Generated by Django 3.2.10 on 2023-02-04 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_auto_20230204_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floors',
            name='building',
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='Floors',
        ),
    ]
