# Generated by Django 3.2.10 on 2022-09-13 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(default=None, max_length=200)),
                ('company_number', models.IntegerField(default=None)),
                ('company_website', models.URLField(default=None)),
                ('company_industry', models.CharField(default=None, max_length=200)),
                ('company_address', models.CharField(default=None, max_length=200)),
                ('name', models.CharField(default=None, max_length=200)),
                ('job_title', models.CharField(default=None, max_length=200)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('email_verified', models.BooleanField(blank=True, null=True)),
                ('contact_no', models.CharField(default=None, max_length=200)),
                ('agree', models.BooleanField()),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=200)),
                ('last_name', models.CharField(default=None, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, default=None, null=True)),
                ('ref_id', models.IntegerField(blank=True, default=None, null=True)),
                ('company_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('company_number', models.IntegerField(blank=True, default=None, null=True)),
                ('business_phone', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('business_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('business_address', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('post_code', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('country', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('industry', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Deactive', 'Deactive')], default=None, max_length=200, null=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('start_date', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('invoice_id', models.IntegerField(blank=True, default=None, null=True)),
                ('payment_terms', models.CharField(blank=True, choices=[('Weekly', 'Weekly'), ('Bi-Weekly', 'Bi-Weekly'), ('Monthly', 'Monthly'), ('Annually', 'Annually'), ('Quartely', 'Quartely')], default=None, max_length=200, null=True)),
                ('output_perference', models.CharField(blank=True, choices=[('Email', 'Email'), ('Print', 'Print'), ('Email And Print', 'Email And Print')], default=None, max_length=200, null=True)),
                ('invoice_footer', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('registration_app_form', models.FileField(blank=True, default=None, null=True, upload_to='registration_app_form/')),
                ('full_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('job_title', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('payment_card', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('expiration', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('account_details_ref', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('payment_on', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('last_payment', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('apply_vat', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('vat_rate', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('contractual_agreement', models.FileField(blank=True, default=None, null=True, upload_to='contractual_agreement/')),
                ('filename_type1', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('filename_type2', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('unique_business', models.ForeignKey(blank=True, default=None, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.join')),
            ],
        ),
    ]
