# Generated by Django 3.2.10 on 2022-09-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20220913_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='company_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
