# Generated by Django 3.2.10 on 2022-09-14 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20220913_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationowner',
            name='created',
        ),
        migrations.RemoveField(
            model_name='organizationowner',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='organizationuser',
            name='created',
        ),
        migrations.RemoveField(
            model_name='organizationuser',
            name='modified',
        ),
    ]
